---
- name: Install qemu-guest-agent
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present

- name: Start qemu-guest-agent
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true
